# -*- coding: utf-8 -*-
"""app5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BouP5_z_A2_G_zpSCgOQZAkyX9pgUnmI
"""

import streamlit as st
from blockchain_utils import deploy_contract
from web3 import Web3

st.set_page_config(page_title="Futures Terminal", layout="wide")
st.title("📉 Futures Smart Contract Interface")

# Connection
w3 = Web3(Web3.HTTPProvider("http://127.0.0.1:8545")) # Local Anvil/Ganache

if st.button("Deploy New Futures Contract"):
    # Call your deploy function here
    st.success("Contract deployed to the local blockchain!")