# -*- coding: utf-8 -*-
"""blockchain_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UR6iUdL-phcb5rnvEixLW-3kW7VrVxVJ
"""

import os
from web3 import Web3
from solcx import compile_standard, install_solc

# Install specific Solidity version
install_solc("0.8.0")

def deploy_contract(w3, account_address, private_key):
    with open("contracts/FuturesContract.sol", "r") as file:
        source_code = file.read()

    # Compile
    compiled_sol = compile_standard({
        "language": "Solidity",
        "sources": {"FuturesContract.sol": {"content": source_code}},
        "settings": {"outputSelection": {"*": {"*": ["abi", "metadata", "evm.bytecode"]}}}
    })

    # Extract ABI and Bytecode
    abi = compiled_sol["contracts"]["FuturesContract.sol"]["FuturesContract"]["abi"]
    bytecode = compiled_sol["contracts"]["FuturesContract.sol"]["FuturesContract"]["evm"]["bytecode"]["object"]

    # Deploy logic via w3.eth.contract...
    return abi, bytecode